### ISSUE TITLE
HTMLStripper crashes on non-HTML messages

### ISSUE THREAD

**Issue by mathieui** [python-otr/gajim-otr#12]
A slightly different (but related) issue from https://github.com/python-otr/gajim-otr/issues/4 ; if I send a plaintext OTR message containing e.g. ``toto* titi = &tata;``, the plugin will traceback and display the raw OTR payload in the chat window.

A simple possible fix would be to wrap the HTMLStripper block on line 600 of otrmodule.py with a try/except and assume that if the stripper fails, it means the message is plaintext. Another one would be to ignore the entity/char refs if they cannot be mapped and add their text to the result instead.

```
15/01/2015 23:19:26 (E) gajim.c.ged Error while running an even handler: <bound method OtrPlugin.handle_incoming_msg of <gotr.otrmodule.OtrPlugin object at 0x7f1ea47b5b50>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gajim/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/home/mathieui/.local/share/gajim/plugins/gotr/otrmodule.py", line 587, in handle_incoming_msg
    stripper.feed((msgtxt or '').decode('utf8'))
  File "/home/mathieui/.local/share/gajim/plugins/gotr/otrmodule.py", line 672, in feed
    HTMLParser.feed(self, data)
  File "/usr/lib/python2.7/HTMLParser.py", line 117, in feed
    self.goahead(0)
  File "/usr/lib/python2.7/HTMLParser.py", line 206, in goahead
    self.handle_entityref(name)
  File "/home/mathieui/.local/share/gajim/plugins/gotr/otrmodule.py", line 657, in handle_entityref
    c = unichr(name2codepoint[name])
KeyError: u'tata'
```

The OTR specification indicates that the message has to be valid UTF-8, and *can* contain html markup, but it doesn't have to be HTML at all, so I assert that this is a bug.

**Comment by afflux** [comment]
IMHO you can't have "maybe HTML" in the content. How are you going to tell if the following message should be parsed as plaintext or HTML?

    /**
    @param  <b>Very important documentation</b>
    */
    toto* titi = &amp;

(By all means, take this to the otr-dev list to discuss)

**Comment by tribut** [comment]
It's obviously impossible to tell whether a message is HTML or not (which is why I have always encouraged entity-encoding `<`, `>` and `&` in OTR messages), but because of this ambiguity, the parser shouldn't fail on malformed input. weechat-otr has a very similar class (`IrcHTMLParser`) which catches KeyError/ValueError and just keeps unknown entities, see [here](https://github.com/mmb/weechat-otr/blob/master/weechat_otr.py#L1034). Depending on where the output is used, a more appropriate output would be `&amp;ENTITY;` of course.

**Comment by afflux** [comment]
I agree that the client should not throw an exception in that case. However, I'm not sure about falling back to displaying the data as text/plain, as this will cause even weirder behavior for the user:

(This only occurs when a sending client is "faulty", ie. sends non-HTML content, so assume the sender is using such a client.)

1. sending user sends `&something;` - receiving user sees `&something;`
2. sending user sends `&` - receiving user sees `&`
3. sending user sends `&amp;` - receiving user sees `&`

Pull requests and suggestions welcome.

**Comment by RolandR** [comment]
Please excuse my ignorance, but why is this even an issue at all?

What does the content of a message concern the OTR plugin?
Shouldn't it just encrypt/decrypt whatever bytes there are in a message and let the client handle any markup it might contain?

**Comment by afflux** [comment]
I agree, the crypto protocol shouldn't have to deal with this. However, the problem stems from the plaintext/html multipart message feature in XMPP and the way pidgin-otr handles it.

Pidgin-otr encrypted the HTML message part, and placed the resulting ciphertext in both the plaintext message part and the HTML message part. This is not a problem if a receiving user indicates they want to read HTML messages.

If they set their client to show unformatted messages instead, the client will ignore the HTML message part and display the plaintext message part, which now contains HTML tags and escaped HTML entities. The receiving user sees this and reports a bug in gaim-otr. Therefore gajim-otr will strip the HTML tags in the displayed plaintext message part. The HTML message part is not modified after decryption.

**Comment by NiklausHofer** [comment]
I wrote a quick patch:

  https://ghostbin.com/paste/a2qpr

This is more of a workaround than a fix, but when I look at @afflux 's last comment, I get a feeling that a proper fix could require actual hard thinking ;)

Here is what it does:
 * Don't attempt to strip Tags from incoming messages
 * Don't HTML encode the outgoing body

I only tested against profanity. Probably does weird stuff if the other end expects HTML encoded messages...

Note: I do NOT suggest you merge this. This is only supposed to be a workaround for those who want a quick solution. Written against v1.9.3 of the plugin.

**Comment by NiklausHofer** [comment]
Hmyeah... Did some actual thinking ;) Wrote this fix. This is NOT the fix from my earlier comment. yay for doing this stuff at 0300. Please test.

Also: When I install the plugin from this repository, it's said to be Version 17.something. The current version of the plugin is version 19.something. There are differences in the code base of the two versions, too. So where is the repository for the actual plugin?

**Comment by afflux** [comment]
> Also: When I install the plugin from this repository, it's said to be Version 17.something. The current version of the plugin is version 19.something. There are differences in the code base of the two versions, too. So where is the repository for the actual plugin?

[This question is answered in the FAQ.](https://github.com/python-otr/gajim-otr/wiki#whats-the-relationship-between-the-plugin-in-gajims-plugin-manager-and-this-repository)

**Comment by NiklausHofer** [comment]
I do, by the way, maintain that [this branch](https://github.com/NiklausHofer/gajim-otr/commits/issue-12) contains a fix. We've tested it for a couple of weeks now and it works just fine. This fix does not contain the security issues that were in earlier versions of the patch.

**Comment by lovetox** [comment]
we applied the solution weechat uses, thanks @tribut for pointing that out
this is patched in version 1.9.6 @ gajim plugin repo
